site_name: HomeLab
theme:
  name: windmill-dark

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Hardware: hardware/index.md
  - Inital Setup: setup/starting.md
  - Network:
    - Switch:
      - Initial Setup: Switch/setup_iniziale.md
      - VLANS Config: Switch/ports_vlans.md
    - OPNsense:
      - Initial Setup: OPNsense/setup.md
      - Notes: OPNsense/notions.md
      - Infrastructure: OPNsense/Infrastructure.md
    - VPN: vpn/tailscale.md
    - Nginx Proxy Manager: nginx-proxy/setup.md
  - Services:
    - Immich: Immich/setup.md
    - Jellyfin: jellyfin/setup.md
    - Czkawka: czkawka/setup.md
    - Pi-hole: pi-hole/setup.md
  - Troubleshooting:
    - Reset password: troubleshooting/reset_password.md
    - Cambiare ID: troubleshooting/spostamento_VM_e_LXC.md
    - Trovare IP nascosto: troubleshooting/Trovare_ip.md
    - Nmap mostra tutti gli indirizzi: troubleshooting/nmap.md
  - Notes:
    - VLAN Notes: network/vlan_notions.md
  - Packet Tracer Lab: packet_tracer_lab/packet_tracer_lab.md